### ISSUE TITLE
Crash vs. Continue

### ISSUE THREAD

**Issue by mvice510** [arnoappenzeller/PiPifier#10]
I enabled the extension in Safari and added it to the toolbar.  When watching Netflix, I clicked the icon and an alert popped up.  I don't remember what it said word for word, but it gave me 2 options, to "crash" and submit a report, or to "continue" with something.  I hit continue, thinking the alert would pop up again should the problem persists, however now nothing happens whatsoever now when I hit the icon.  I  deleted the extension/app from my computer, went back to the App Store to reinstall it, set it up in Safari again- yet it continues to do nothing when I click on it- the alert doesn't even pop up anymore.  HELP!

mVice

**Comment by arnoappenzeller** [comment]
Hello mVice,

At first sorry that PiPifier doesn't work as it should. But I find your report very hard to read and hard to understand what the real issue is. Also I don't find it very nice of you to post a one star review because it is not working for you yet without giving the chance to help you. I hope you know the impact that negative and especially one star reviews can have for an app.

But now to your problem:
From what I understand the app crashed for you. There is now a new version 1.2 in the AppStore. I recommend the following steps for a clean reinstall:
1. Deactivate the extension in Safari
2. Now go to Launchpad (Press F4) and hold the mouse on PiPifier. Then delete it by pressing the X-Button.
3. Reinstall the app from the AppStore
4. Launch it one time
5. Add the extension to Safari again

Now it should work. Note that you need to interact at least one with the Netflix video (press pause then play again) for PiPifier to work correctly

I hope this helps
