### ISSUE TITLE
PiP is not working, if Safari in full screen mode

### ISSUE THREAD

**Issue by paulelms** [arnoappenzeller/PiPifier#4]

**Comment by arnoappenzeller** [comment]
Thanks for this issue. Never use Fullscreen so I haven't seen it before.

For some reason it must be related with the button of PiPifier because for example on YT both the double right click and entering `document.querySelectorAll('video')[0].webkitSetPresentationMode('picture-in-picture');` to console works in fullscreen but PiPifier not.

Will investigate this

**Comment by arnoappenzeller** [comment]
This is looking like a bug in the Safari Extension framework.

If Safari is not in fullscreen `window.getActiveTab` in  `toolbarItemClicked(in window: SFSafariWindow)` returns the current tab as expected but if it is in fullscreen it returns nil.

This doesn't look right for me.

**Comment by thetinguy** [comment]
This might help: https://developer.apple.com/library/prerelease/content/documentation/Tools/Conceptual/SafariExtensionGuide/WorkingwithWindowsandTabs/WorkingwithWindowsandTabs.html

**Comment by arnoappenzeller** [comment]
Those docs are about the old JS API but should apply as well. 

But I'm not sure if I'm missing something but it can't be right that a window in fullscreen returns nil for activeTab and the actual value when not in fullscreen. 

Think I'm gonna file a radar

**Comment by espenbye** [comment]
Get the active window using `SFSafariApplication.getActiveWindow` first, then continue with `getActiveTab`. That works on fullscreen as well.

**Comment by arnoappenzeller** [comment]
Thanks to @espenbye this is resolved with the latest commit!

Still feels a bit weird that the window from the call has nil for page
