### ISSUE TITLE
No captioning/subtitles in PIP

### ISSUE THREAD

**Issue by markdeafmcguire** [arnoappenzeller/PiPifier#8]
Not sure if this is where I submit an issue with PIP. It is installed and working as advertised but when I use it for Netflix, it appears the captioning is left behind on the tab (as opposed to being part of the PIP screen).

I have included a screenshot for your viewing pleasure. As you can see in the screenshot, the captioning (yellow fonts) is displayed in the tab with the PIP playing in the corner.

Consider this an accesibility issue which could be a huge advantage if you want to secure more users who would love to watch this without sound in the background.

<img width="1280" alt="screen shot 2016-10-06 at 6 09 43 pm" src="https://cloud.githubusercontent.com/assets/22669701/19172574/93a11312-8bf0-11e6-9149-53443eb8f80f.png">

For some reason, the screenshot does not display the video image of the PIP in relation to the captioning (I tried multiple times and got same results). But kudos on your extension. If it included captioning, I would give it a five star.

**Comment by arnoappenzeller** [comment]
Hi,

I already heard about this issue but I guess at the moment that with the way Netflix showing the subtitles it is not possible to add the subtitles to the PiP window.

Netflix show the subtitles in a separate element of the webpage so that it is not part of the window. As of what I know there is no way to add this to the PiP window.
<img width="1241" alt="bildschirmfoto 2016-10-17 um 00 47 10" src="https://cloud.githubusercontent.com/assets/4069713/19421521/79f05476-9403-11e6-89fe-ba63a255ecf2.png">

I will close this issue for now since I don't see an solution but I will keep an eye on it.

Sorry!
